# Generated by Django 4.1 on 2023-05-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0003_passenger"),
    ]

    operations = [
        migrations.RenameField(
            model_name="passenger",
            old_name="flight",
            new_name="flights",
        ),
    ]
